
export const SET_USER = 'SET_USER'
export const FETCH_REGISTER_USER = 'FETCH_REGISTER_USER';
export const FETCH_LOGIN_USER = 'FETCH_LOGIN_USER';
export const FETCH_AUTOLOGIN_USER = 'FETCH_AUTOLOGIN_USER';
export const FETCH_LOGOUT = 'FETCH_LOGOUT';

export const FETCH_SET_USER_INFO = 'FETCH_SET_USER_INFO';
export const FETCH_SET_USER_PICTURE = 'FETCH_SET_USER_PICTURE';


export const UPDATE_CLOTHS = 'UPDATE_CLOTHS'
export const TOGGLE_CHOOSED_CLOTH = 'TOGGLE_CHOOSED_CLOTH'
export const FETCH_CREATE_CLOTH = 'FETCH_CREATE_CLOTH'
export const FETCH_GET_CLOTHS = 'FETCH_GET_CLOTHS'