
export const SET_USER = 'SET_USER'
export const SET_MAILCODE_STATUS = 'SET_MAILCODE_STATUS'
export const FETCH_CHECK_MAILCODE = 'FETCH_CHECK_MAILCODE';
export const FETCH_SET_MAILCODE = 'FETCH_SET_MAILCODE'
export const FETCH_REGISTER_USER = 'FETCH_REGISTER_USER';
export const FETCH_LOGIN_USER = 'FETCH_LOGIN_USER';
export const FETCH_AUTOLOGIN_USER = 'FETCH_AUTOLOGIN_USER';
export const FETCH_LOGOUT = 'FETCH_LOGOUT';
export const FETCH_CHANGE_PASSWORD = 'FETCH_CHANGE_PASSWORD';

export const FETCH_SET_USER_INFO = 'FETCH_SET_USER_INFO';
export const FETCH_SET_USER_PICTURE = 'FETCH_SET_USER_PICTURE';


export const UPDATE_CLOTHS = 'UPDATE_CLOTHS'
export const ADD_CLOTHS = 'ADD_CLOTHS'
export const UPDATE_CLOTH_IMG = 'UPDATE_CLOTH_IMG'
export const DELETE_CLOTHS = 'DELETE_CLOTHS'
export const TOGGLE_CHOOSED_CLOTH = 'TOGGLE_CHOOSED_CLOTH'
export const FETCH_CREATE_CLOTH = 'FETCH_CREATE_CLOTH'
export const FETCH_GET_CLOTHS = 'FETCH_GET_CLOTHS'
export const FETCH_DELETE_CLOTH = 'FETCH_DELETE_CLOTH'
export const FETCH_GET_CLOTHS_BY_ID = 'FETCH_GET_CLOTHS_BY_ID'



export const UPDATE_LOOKS = 'UPDATE_LOOKS'
export const FETCH_CREATE_LOOK = 'FETCH_CREATE_LOOK'
export const FETCH_GET_LOOKS = 'FETCH_GET_LOOKS'
export const FETCH_GET_LOOK_IDS = 'FETCH_GET_LOOK_IDS'
export const FETCH_DELETE_LOOKS = 'FETCH_DELETE_LOOKS'
export const FETCH_TOGGLE_LIKE_LOOK = 'FETCH_TOGGLE_LIKE_LOOK'
export const FETCH_CHANGE_CATEGORY_LOOK = 'FETCH_CHANGE_CATEGORY_LOOK'


export const UPDATE_LOOKS_ADMIN = 'UPDATE_LOOKS_ADMIN'
export const FETCH_GET_LOOKS_ADMIN = 'FETCH_GET_LOOKS_ADMIN'
export const FETCH_GET_LOOK_IDS_ADMIN = 'FETCH_GET_LOOK_IDS_ADMIN'
export const FETCH_UPDATE_LOOK_ADMIN = 'FETCH_UPDATE_LOOK_ADMIN'