
export const SET_USER = 'SET_USER'
export const FETCH_REGISTER_USER = 'FETCH_REGISTER_USER';
export const FETCH_LOGIN_USER = 'FETCH_LOGIN_USER';
export const FETCH_AUTOLOGIN_USER = 'FETCH_AUTOLOGIN_USER';
export const FETCH_LOGOUT = 'FETCH_LOGOUT';

export const FETCH_SET_USER_INFO = 'FETCH_SET_USER_INFO';